name: terraform-20-network-hub

on:
  pull_request:
    paths:
      - "infra/20-network-hub/**"
  push:
    branches: ["main"]
    paths:
      - "infra/20-network-hub/**"

concurrency:
  group: tf-20-network-hub
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: infra/20-network-hub
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - run: terraform fmt -check
      - run: terraform init
      - run: terraform validate
      - run: terraform plan -lock-timeout=5m

  apply:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: infra/20-network-hub
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - run: terraform init
      - run: terraform apply -auto-approve -lock-timeout=5m
